[package]
name = "toecs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "toecs_derive",
]

[dependencies]
toecs_derive = { path = "./toecs_derive", version = "0.1.0" }

anyhow = "1.0.52"
atomic_refcell = "0.1.8"
downcast-rs = "1.2.0"
rustc-hash = "1.1.0"

