[package]
name = "toecs_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = "1.0.98"
darling = "0.14.1"

[dev-dependencies]
toecs = { path = "../" }
