[package]
name = "toecs_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.33"
quote = "1.0.10"
syn = "1.0.82"
darling = "0.13.1"

[dev-dependencies]
toecs = { path = "../" }
